### ISSUE TITLE
`ChainBuildException: Cycle detected` in 2.0.2

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-logging-sentry#161]
When updating the Quarkus Registry to 2.0.2, I get the following build error:

See https://github.com/quarkusio/registry.quarkus.io/actions/runs/6240179698/job/16939694647?pr=216
 
```
java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
		   io.quarkus.arc.deployment.ArcProcessor#registerBeans produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem
		to io.quarkus.logging.sentry.deployment.SentryProcessor#addSentryLogHandler produced class io.quarkus.deployment.builditem.LogHandlerBuildItem
		to io.quarkus.deployment.logging.LoggingResourceProcessor#setupLoggingRuntimeInit produced class io.quarkus.deployment.logging.LoggingSetupBuildItem
		to io.quarkus.flyway.FlywayProcessor#createBeans produced class io.quarkus.arc.deployment.AdditionalBeanBuildItem
		to io.quarkus.arc.deployment.BeanArchiveProcessor#build produced class io.quarkus.arc.deployment.BeanArchiveIndexBuildItem
		to io.quarkus.arc.deployment.AutoProducerMethodsProcessor#annotationTransformer produced class io.quarkus.arc.deployment.AnnotationsTransformerBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#initialize produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem
		to io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#transactionContext produced class io.quarkus.arc.deployment.ContextRegistrationPhaseBuildItem$ContextConfiguratorBuildItem
		to io.quarkus.arc.deployment.ArcProcessor#registerBeans
```

**Comment by mschorsch** [comment]
We have the same problem

**Comment by ia3andy** [comment]
Ok looking, weird that it slipped through CI

**Comment by ia3andy** [comment]
@geoand any idea on how to read this exception?

**Comment by geoand** [comment]
You'll need to follow the cycle of produced build items mentioned in the exception and then try and break it, mostlikely by spliting some method so it does not produce on of those build items.

**Comment by ia3andy** [comment]
@gastaldi I can't reproduce the error, it must be related to FlyWay I guess

**Comment by ia3andy** [comment]
Ok indeed.. reproduced

**Comment by mschorsch** [comment]
> @gastaldi I can't reproduce the error, it must be related to FlyWay I guess

This is likely. All projects with flyway integrated break. Projects without flyway build without an error.

**Comment by ia3andy** [comment]
I am working on a fix

**Comment by ia3andy** [comment]
@mschorsch are you able to give a try to the fix?

**Comment by mschorsch** [comment]
> @mschorsch are you able to give a try to the fix?

With your fix we cannot reproduce the eror anymore 👍

**Comment by ia3andy** [comment]
@mschorsch 2.0.3 is available cheers!
