### ISSUE TITLE
Add static tags via properties

### ISSUE THREAD

**Issue by HerrDerb** [quarkiverse/quarkus-logging-sentry#219]
Currently it is only possible to add context-tags for each event with `quarkus.log.sentry.context-tags`

As I have a sentry project to which multiple server application report, I would love also to be able to set static tags via properties.
e.g. `quarkus.log.sentry.tags."my.custom.tag"=myAppId`

**Comment by ia3andy** [comment]
@HerrDerb would you contribute it? it should be fairly easy to add :)
