### ISSUE TITLE
yml config doesn't work for quarkus-logging-sentry

### ISSUE THREAD

**Issue by henka-rl** [quarkiverse/quarkus-logging-sentry#88]
Because 'enable' is defined as `@ConfigItem(name = ConfigItem.PARENT)` it doesn't work with yml config.
Changing this to `@ConfigItem(defaultValue = "false")` solves the issue, but it breaks current properties config.
`quarkus.log.sentry=true` must be changed to `quarkus.log.sentry.enable=true`

**Comment by ia3andy** [comment]
In yaml, you have to do this:
```yaml
quarkus:
  log:
    sentry:
      ~: true
```
